---
title: "Siniestros de tránsito en la Región Metropolitana"
author: "Camila Villagrán"
date: "-11-2021"
output: html_document
---

```{r echo =FALSE, warning=FALSE, message=FALSE}
setwd("..")

source(here::here("Codigo/Main.R"), local = knitr::knit_global(), 
       encoding = "UTF-8")

```
#### I. Introducción
En los últimos años, hemos podido evidenciar el aumento de vehículos como medio de transporte. Según la Asociación Nacional Automotriz de Chile (ANAC), al finalizar octubre del 2021, el mercado de vehículos livianos y medianos finalizo con la venta de 38.551 unidades nuevas y un crecimiento de 6.4% en comparación a octubre del 2020. Siendo octubre de este año, el de mayores ventas desde que se tiene registro de estos datos. Hoy en día, tener un auto se ha vuelto algo común, cómodo y esencial para muchos. Esto se debe a que nos permiten ir de un lugar a otro, de manera más rápida, eficaz y lo más importante es que nos ahorran tiempo. 

Si bien tener un vehículo, trae muchos beneficios, especialmente en estos tiempos de pandemia, debido a que son una herramienta para evitar contagios. Al mismo tiempo, estos son los causantes de muchos accidentes. Según el informe elaborado por la Comisión Nacional de Seguridad de Tránsito (CONASET), durante el año 2020, se registraron un total de 64.707 siniestros de tránsito a lo largo de todo el país, siendo la región Metropolitana la que presentó más siniestro, obteniendo una cifra de 19.047.

Es por esto, que, a través de este informe, realizaremos un análisis estadístico a una base de datos, la que contiene siniestros de tránsito en la Región Metropolitana en Chile, durante el año 2018. Esta fue obtenida de la CONASET, para así poder dar a conocer aquellas comunas en donde se presentan una mayor y menor cantidad de siniestros, fallecidos, etc. A su vez, poder agrupar las comunas respecto a sus distritos correspondientes y así sacan inferencia de esta información.

Este informe se dividirá en tres partes. En primer lugar, se presentarán los datos a analizar, explicando sus variables y características. En la segunda parte, se entregarán los resultados de nuestra investigación. Además, se hará una inferencia de estos resultados, para así poder entregar una conclusión de lo observado, respecto a los siniestros ocurridos en la Región Metropolitana, cuya conclusión será presentada en la última parte.


#### II. Descripción de los datos
En la base de datos inicial, se nos presenta un total de 1697 observaciones, correspondiente a los siniestros de transito, cabe mencionar que está base de datos, no contiene la cantidad total de los siniestros de la Región Metropolitana, sino solamente aquellos que fue posible geocodificar en la zona urbana, que son aproximadamente el 90%. Además, la base de datos contiene variables que no eran de interés para nuestro proyecto, es por eso, que realizaremos una limpieza para quedarnos con aquellas variables que son representativa y agregaremos 2 variables, que no venían incluidas, las cuales son: Intersección y Distrito.

#### III. Resultados

#### IV. Conclusión

#### V. Referencias

https://www.anac.cl/wp-content/uploads/2021/11/10-ANAC-Mercado-Automotor-Octubre-2021.pdf

https://www.anac.cl/wp-content/uploads/2019/01/12-Informe-del-Mercado-Automotor-Diciembre-2018.pdf

https://www.conaset.cl/wp-content/uploads/2021/06/Chile-2020.pdf
